/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmfilesystem_free: (a: number, b: number) => void;
export const __wbg_wasmgit_free: (a: number, b: number) => void;
export const __wbg_wasmstore_free: (a: number, b: number) => void;
export const __wbg_wasmtopologystore_free: (a: number, b: number) => void;
export const wasmstore_add_comment: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const wasmstore_add_label: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const wasmstore_bulk_update: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const wasmstore_compute_solid_score: (a: number, b: number, c: number) => [number, number, number];
export const wasmstore_create_issue: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
export const wasmstore_export: (a: number) => [number, number, number, number];
export const wasmstore_get_all_labels: (a: number) => [number, number, number, number];
export const wasmstore_get_pagerank_hotspots: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const wasmstore_get_topology_for_viz: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmstore_get_vitals: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmstore_list_issues: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmstore_load: (a: number, b: number, c: number) => [number, number];
export const wasmstore_new: () => number;
export const wasmstore_remove_label: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const wasmstore_search: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmstore_update_issue: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const wasmtopologystore_edge_count: (a: number) => number;
export const wasmtopologystore_get_betti: (a: number) => [number, number];
export const wasmtopologystore_get_edges_for_viz: (a: number) => [number, number, number, number];
export const wasmtopologystore_get_hotspots: (a: number, b: number) => [number, number, number, number];
export const wasmtopologystore_get_nodes_for_viz: (a: number) => [number, number, number, number];
export const wasmtopologystore_get_solid_score: (a: number) => number;
export const wasmtopologystore_is_loaded: (a: number) => number;
export const wasmtopologystore_load_topology: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmtopologystore_new: () => number;
export const wasmtopologystore_node_count: (a: number) => number;
export const wasmtopologystore_search_symbols: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const wasmfilesystem_new: () => number;
export const wasmgit_new: () => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
